services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    build: .
    ports:
      - 80:5000
    environment:
      - PORT=5000
      - REDIS_URL=redis://storage
    depends_on: 
      - storage