version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

# services:
#   storage:
#     image: redis
#     volumes:
#       - ./data:/data
#   counter:
#     image: node:19.8
#     working_dir: /app
#     volumes:
#       - ./:/app
#     ports:
#       - 80:5000
#     environment:
#       - PORT=5000
#       - REDIS_URL=redis://storage
#     command: npm run dev
#     depends_on: 
#       - storage